
CREATE TABLE public.client (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cpf varchar(255) NULL,
	email varchar(255) NULL,
	endereco varchar(255) NULL,
	nome varchar(255) NULL,
	telefone varchar(255) NULL,
	CONSTRAINT client_pkey PRIMARY KEY (id)
);

CREATE TABLE public.book (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ano_lancamento int4 NULL,
	autor varchar(255) NULL,
	codigo varchar(255) NULL,
	descricao varchar(255) NULL,
	status varchar(255) NULL,
	titulo varchar(255) NULL,
	CONSTRAINT book_pkey PRIMARY KEY (id),
	CONSTRAINT book_status_check CHECK (((status)::text = ANY ((ARRAY['LIVRE'::character varying, 'EMPRESTADO'::character varying])::text[]))),
	CONSTRAINT uk_book_codigo UNIQUE (codigo)
);

CREATE TABLE public.loan (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	loan_date timestamptz(6) NULL,
	due_date timestamptz(6) NULL,
	status varchar(255) NULL,
	book_id int8 NULL,
	client_id int8 NULL,
	CONSTRAINT loan_pkey PRIMARY KEY (id),
	CONSTRAINT loan_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'RETURNED'::character varying])::text[])))
);

ALTER TABLE public.loan ADD CONSTRAINT fk_loan_client FOREIGN KEY (client_id) REFERENCES public.client(id);
ALTER TABLE public.loan ADD CONSTRAINT fk_loan_book FOREIGN KEY (book_id) REFERENCES public.book(id);